<?php

/**
 * (c) Meritoo.pl, http://www.meritoo.pl
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Meritoo\CommonBundle\Service;

use Meritoo\CommonBundle\Service\Base\BaseService;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\RouterInterface;

/**
 * Serves responses
 *
 * @author    Meritoo <github@meritoo.pl>
 * @copyright Meritoo <http://www.meritoo.pl>
 */
class ResponseService extends BaseService
{
    /**
     * The router
     *
     * @var RouterInterface
     */
    private RouterInterface $router;

    /**
     * Class constructor
     *
     * @param RouterInterface $router The router
     */
    public function __construct(RouterInterface $router)
    {
        $this->router = $router;
    }

    /**
     * Returns the "redirect response" that is used to redirect to url generated by given route and parameters
     *
     * @param string $routeName       The name of the route. Used to build url used for redirection.
     * @param array  $routeParameters (optional) An array of parameters. Used to build url used for redirection.
     * @return RedirectResponse
     */
    public function getRedirectResponse(string $routeName, array $routeParameters = []): RedirectResponse
    {
        $url = $this->router->generate($routeName, $routeParameters);

        return new RedirectResponse($url);
    }
}
